version: "3.9"
services:
    backend:
        build: ./backend
        image: rating_backend
        container_name: backend
        restart: always
        # env_file: ./backend/.env
        networks:
            - front-back
        ports:
            - 8010:8010
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./backend:/backend
    frontend:
        build: ./frontend
        image: rating_frontend
        container_name: frontend
        # env_file: ./frontend/.env
        networks:
            - front-back
        links:
            - backend
        ports:
            - 3000:3000
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./frontend:/frontend
networks:
    front-back:
        driver: bridge