version: "3.9"
services:
    backend:
        build: backend/.
        image: rating_backend
        container_name: backend
        # env_file: ./backend/.env
        networks:
            - front-back
        ports:
            - 8010:8010
        volumes:
            - /opt/backend/node_modules
            - /opt/backend/vendor
            - ./backend:/opt/backend
    frontend:
        build: frontend/.
        image: rating_frontend
        container_name: frontend
        # env_file: ./frontend/.env
        networks:
            - front-back
        depends_on:
            - backend
        ports:
            - 3000:3000
        volumes:
            - /opt/frontend/node_modules
            - ./frontend:/opt/frontend
networks:
    front-back:
        driver: bridge